### ISSUE TITLE
Running gwbse calculations

### ISSUE THREAD

**Issue by mbarbry** [votca/xtp#138]
Hi,

I'm a new user of Votca-XTP. I managed to run edft and idft calculations using the DFT packages nwchem and obtained the transfer integral. Now I would like to use the gwbse module of xtp in order to obtain more accurate HOMO/LUMO energies. However, I could find only very little documentation on this module and I don't have any clues how to run such calculations. Does there is some examples somewhere? Could you provide me some guideline?

Thanks in advance,
Marc Barbry

**Comment by baumeier** [comment]
Dear Marc,

we are currently writing the documentation of the GW-BSE module since its development was very much in flux until recently. 
If you can send me (baumeier@votca.org) some details about what system you are working on and which setup you plan to use (I assume based on DFT runs in nwchem? which basis set, functional etc), I can provide you with the necessary input files and clues how to run the tools.

Cheers,
Bjoern

**Comment by JensWehner** [comment]
closed by #152
