### ISSUE TITLE
Energy and gradient mode for GWBSE

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#407]
Instead of performing a full geometry optimization, enable a mode that for a given geometry calculates its energy and the gradient/forces (see e.g. orca‘s engrad mode).
Useful for integration in ASE and/or use with external optimizers.

**Comment by baumeier** [comment]
Since gradients are anyway calculated numerically, we can calculate *all* gradients (GW, BSE) and all calculated states at the same time.
Should also be stored/accessed in the hdf5 file.

**Comment by JensWehner** [comment]
I do not think it should be part of the orbitals file, but we can add an outer layer which stores the orbitals of all relevant contributions

**Comment by baumeier** [comment]
I was thinking about storing the gradients of all states, not the states themselves.

**Comment by JensWehner** [comment]
ahh okay maybe you are right and we store it in the orbitals but somehow I think it does not belong in orbitals but somewhere more in  a geoopt.hdf5 file

**Comment by baumeier** [comment]
That is a possibility too. In any case I want to avoid txt files.

**Comment by rubengerritsen** [comment]
This discussion makes me wonder about the orbital files in general, currently I have only seen a single group (QMdata) in my orbital files, in which all the orbital en excited state data are stored. Are there any other "top-level" groups? If not (or only a small number) why not make a group in the .orb files for the gradient/forces (or is this the outer layer Jens is talking about)? Furthermore to me it seems better to combine as much of the votca output as possible into a single file, in particular for the integration with for example ASE and python in general. It seems better to only have to keep track of one file instead of multiple files.

**Comment by JensWehner** [comment]
So my unsorted thoughts:

- The .orb (orbital files) are basically the content of the orbitals.h class. Currently the data format of the .orb files is HDF5. I still believe the orb file should only contain information from the orbitals class. As geometry optimisation requires information from multiple orbitals files, I do not think it should be in the current .orb file, because none of the functionality of the orbitals object needs the forces/gradients. I also think the orbitals class is big enough as it is and we should not add more to it. 

- We should actually serialize the basissets as well and put them into the .orb file. 

- As @rubengerritsen correctly states all the orbitals stuff is saved in the QMdata group. So the current .orb files could be extended with other groups, but that requires that the .orb file is not only a serialisation of the orbitals object but a full checkpoint file of the qm calculation. So we maybe should rename it. It could i.e. also save the optimisation trajectory. 

- Concerning only one file, XTP at the moment produces 3 different kind of .hdf5 files
1) .orb files 2) state files for the kmc with mapping and coupling and stuff 3) qmmm checkpoint files, which save the state of a qmmm calculation

- Otherwise XTP also produces .mps .xyz .xml .dat .cube files for various calculators..

- We can make this a bigger discussion, but I think we should create a more general issue/project.

**Comment by baumeier** [comment]
TBD in Python
