### ISSUE TITLE
unit_test_sigma_cda sefaults on fedora sometimes 

### ISSUE THREAD

**Issue by junghans** [votca/xtp#604]
From https://github.com/votca/votca/runs/1487549992?check_suite_focus=true

```
267/297 Test #272: unit_test_sigma_cda ................................***Exception: SegFault  0.34 sec
Running 1 test case...
unknown location(0): fatal error: in "sigma_cda_test/sigma_full": memory access violation at address: 0x00000028: no mapping at fault address
../xtp/src/tests/test_sigma_cda.cc(92): last checkpoint

*** 1 failure is detected in the test module "sigma_test"
```

**Comment by JensWehner** [comment]
do you have any more information on it?

**Comment by junghans** [comment]
Just the above log file.

**Comment by JensWehner** [comment]
Did it happen again?

**Comment by junghans** [comment]
yes, today in https://github.com/votca/votca/pull/614

**Comment by JensWehner** [comment]
So locally I could produce this output :+1: 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==12200==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x7f50e0cf670d bp 0x000000000000 sp 0x7f5083774e70 T3)
==12200==The signal is caused by a READ memory access.
==12200==Hint: address points to the zero page.
    #0 0x7f50e0cf670d  (/lib64/libomp.so+0x7870d)
    #1 0x7f50e0cf15bd in __kmpc_dispatch_next_8 (/lib64/libomp.so+0x735bd)
    #2 0x7f50e2583e40 in .omp_outlined._debug__.6 /home/votca/votca/xtp/src/libxtp/gwbse/sigma_base.cc:58:3
    #3 0x7f50e2583e40 in .omp_outlined..7 /home/votca/votca/xtp/src/libxtp/gwbse/sigma_base.cc:57:1
    #4 0x7f50e0d19042 in __kmp_invoke_microtask (/lib64/libomp.so+0x9b042)
    #5 0x7f50e0cbdbac  (/lib64/libomp.so+0x3fbac)
    #6 0x7f50e0cbcc48  (/lib64/libomp.so+0x3ec48)
    #7 0x7f50e0d02c7d  (/lib64/libomp.so+0x84c7d)
    #8 0x7f50e0c66268 in start_thread (/lib64/libpthread.so.0+0x9268)
    #9 0x7f50d51f52d2 in clone (/lib64/libc.so.6+0x1012d2)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libomp.so+0x7870d) 
Thread T3 created by T0 here:
    #0 0x440f66 in pthread_create (/home/votca/builddir/xtp/src/tests/unit_test_sigma_cda+0x440f66)
    #1 0x7f50e0d01341  (/lib64/libomp.so+0x83341)

==12200==ABORTING

**Comment by junghans** [comment]
Seems to be fixed.
